apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: vladtraum/kub-network-app-v3-users:latest
          env:
            - name: AUTH_DOMAIN
              value: "auth-service.default" # built-in core dns feature. Works inside the cluster based on service name. default - namespace